api_platform:
    title: Florajet Test V1.0
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']

    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

    http_cache:
        invalidation:
            enabled: true
            varnish_urls: [ '%env(VARNISH_URL)%' ]
            purger: 'api_platform.http_cache.purger.varnish.xkey'
        public: true
    defaults:
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
            invalidation:
                xkey:
                    glue: ', '
